# Generated by Django 5.2.7 on 2026-06-07 07:30

from django.db import migrations


def setup_social_apps(apps, schema_editor):
    Site = apps.get_model("sites", "Site")
    SocialApp = apps.get_model("socialaccount", "SocialApp")

    # Ensure Site records exist
    site_local, _ = Site.objects.get_or_create(
        id=1,
        defaults={"domain": "127.0.0.1:8000", "name": "PSUSphere Local"},
    )
    site_prod, _ = Site.objects.get_or_create(
        id=2,
        defaults={"domain": "oaappp.pythonanywhere.com", "name": "PSUSphere Production"},
    )

    # --- Google ---
    google_app, created = SocialApp.objects.get_or_create(
        provider="google",
        defaults={
            "name": "Google Login",
            "client_id": "",
            "secret": "",
        },
    )
    google_app.sites.add(site_local, site_prod)

    # --- GitHub ---
    github_app, created = SocialApp.objects.get_or_create(
        provider="github",
        defaults={
            "name": "Github Login",
            "client_id": "",
            "secret": "",
        },
    )
    github_app.sites.add(site_local, site_prod)


def reverse_setup(apps, schema_editor):
    SocialApp = apps.get_model("socialaccount", "SocialApp")
    SocialApp.objects.filter(provider__in=["google", "github"]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("studentorg", "0001_initial"),
        ("socialaccount", "0006_alter_socialaccount_extra_data"),
    ]

    operations = [
        migrations.RunPython(setup_social_apps, reverse_setup),
    ]
