# Generated by Django 5.2.7 on 2026-06-07 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentorg', '0001_initial'),
    ]

    operations = [
    ]
